//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Student
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Please Enter Name.")]
        public string Name { get; set; }

        [Required(ErrorMessage ="Please Enter Email.")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Please Enter Division.")]
        [StringLength(1)]
        public string Division { get; set; }

        [Required(ErrorMessage = "Please Enter City.")]
        [StringLength(10)]
        public string City { get; set; }

        [Required(ErrorMessage ="Please Enter Contact no.")]
        public Nullable<decimal> Contact { get; set; }
        public Nullable<int> GenderId { get; set; }
        public Nullable<int> StandardId { get; set; }

        public string Gender { get; set; }

        public virtual GenderTable GenderTable { get; set; }
        public virtual StandardTable StandardTable { get; set; }
    }
}
