//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarberShopSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Haircut
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Haircut()
        {
            this.Bookings = new HashSet<Booking>();
        }
    
        public int HaircutId { get; set; }
        public Nullable<int> HairStylistId { get; set; }
        public Nullable<int> ShopId { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Name { get; set; }
        public string HaircutType { get; set; }
    
        public virtual BarberShop BarberShop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
        public virtual HairStylist HairStylist { get; set; }
    }
}
