//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarberShopSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int ReviewId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ShopId { get; set; }
        public string ReviewDescription { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual BarberShop BarberShop { get; set; }
        public virtual User User { get; set; }
    }
}
