//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarberShopSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BarberShopEntities2 : DbContext
    {
        public BarberShopEntities2()
            : base("name=BarberShopEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BarberShop> BarberShops { get; set; }
        public virtual DbSet<Booking> Bookings { get; set; }
        public virtual DbSet<Haircut> Haircuts { get; set; }
        public virtual DbSet<HairStylist> HairStylists { get; set; }
        public virtual DbSet<Review> Reviews { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserTypes2> UserTypes2 { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }

        public System.Data.Entity.DbSet<BarberShopSystem.Models.ViewModel.UserReg> UserRegs { get; set; }
    }
}
