//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarberShopSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Booking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Booking()
        {
            this.Payments = new HashSet<Payment>();
        }
    
        public int BookingId { get; set; }
        public Nullable<int> ShopId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> HairStylistId { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public Nullable<int> HaircutId { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        [Required]
        public Nullable<System.DateTime> BookingDate { get; set; }
    
        public virtual BarberShop BarberShop { get; set; }
        public virtual Haircut Haircut { get; set; }
        public virtual HairStylist HairStylist { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
    }
}
